### ISSUE TITLE
[Tracking] The Road to 1.x

### ISSUE THREAD

**Issue by crutchcorn** [TanStack/form#813]
As of today, **I'm officially announcing that we've gone from a `beta` release to an `rc` release**.

This means that we're **stable** and do not intend to introduce breaking changes unless things go _**really**_ wrong

However, **prior to launching v1**, I'd like us to address the following:

- [x] https://github.com/TanStack/form/pull/1179
- [x] https://github.com/TanStack/form/pull/1035
- [x] https://github.com/TanStack/form/pull/1038
     - [x] Upstream PR: https://github.com/TanStack/store/pull/40
- [x] https://github.com/TanStack/form/issues/753
- [x] https://github.com/TanStack/form/issues/746
- [x] https://github.com/TanStack/form/issues/748
- [x] https://github.com/TanStack/form/pull/656
- [x] https://github.com/TanStack/form/pull/925
- [x] https://github.com/TanStack/form/pull/1104
- [x] https://github.com/TanStack/form/issues/1023

In addition, I'd like to work with a company to integrate TanStack Form in a production-ready codebase and have their QA/Product department/s take a look at the end-user experience.

> If you'd like to help us test this in your company, reach out to me [via Twitter](https://twitter.com/crutchcorn/), [our Discord](https://tlinz.com/discord), [our enterprise support page](https://tanstack.com/dedicated-support), or my email (easily found in [a commit patch](https://github.com/TanStack/form/commit/4e4a3ae12c3f2b3458ab1bd5f1beaf161f7b6995.patch))

I know 1.x has taken a _long_ time to get here. This is because I wanted to wait until we were _extremely_ confident in what we're shipping. I'm very happy with how things are going today, but don't want to ship a v1, then a v2, then a v3 quickly. I want us to stay stable for some time in the future. 

> Reference to original issue comment about 1.x release: https://github.com/TanStack/form/issues/660#issuecomment-2194817140

**Comment by crutchcorn** [comment]
To anyone following along with this issue, I'm making a minor adjustment to add this feature prior to 1.x:

https://github.com/TanStack/form/pull/925

Which may technically introduce a small breaking change for a fraction of users via a change in the TypeScript typings (not behavior). Apologies for this, but this is a much better change for your apps, promise!

**Comment by crutchcorn** [comment]
Wanted to leave this here as a clear update for some of the breaking changes we've been forced to make since announcing our RC phase:

https://github.com/TanStack/form/issues/1044

Sorry again, everyone.

**Comment by crutchcorn** [comment]
Quick status update for anyone following along with the v1 release: https://github.com/TanStack/form/issues/1044#issuecomment-2594013065

**Comment by crutchcorn** [comment]
This is it folks! We're down to the final PR to finalize prior to v1, and it's a big one (reusable form components!):

https://github.com/TanStack/form/pull/1179

Please review this and let me know what you think of the proposed API. Also, please reply to this issue if you think there are any other pressing problems we need to resolve prior to v1. Keep in mind though that we won't be resting on our laurels once we ship v1, so smaller bugs and such may not make the cut; it's always a balancing game to ship a v1 stable. 😊
